# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ci-cd pipeline for django application


#PYTHON -->


# on:
#   push:
#     tags:
#       - "v*"

on:
  push:
    branches: ['django']


jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.11.14] 

    steps:
    - uses: actions/checkout@v4
    - name: Use Python version ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt
    
    # - name: Test dependencies
    #   run: pip install -e ".[dev]"

    # - name: Run Pytest
    #   run: pytest

    - name: DOCKER BUILD & RUN 
      run : |
        docker compose --profile app -f docker-compose.yml build
        docker compose --profile app -f docker-compose.yml up -d

        docker compose restart nginx

    

    # - name: Docker build
    #   run: docker build -t ci-cd-test:latest .

    # - name: Run Container
    #   run: docker run -d -p 3000:5500 ci-cd-test:latest

    # - name: BUILD & PUSH TO HUB
    #   env:
    #      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
    #      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    #   run: |  
    #     echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    #     # docker build -t $DOCKER_USERNAME/ci-cd-test:latest .
    #     # docker push $DOCKER_USERNAME/ci-cd-test:latest

    #     docker compose -f docker-compose.yml build
    #     docker compose -f docker-compose.yml up -d
    




    


